name: Publish to gh-pages

on:
  workflow_dispatch:
  repository_dispatch:
    push:
      branches:
        - main
        - test-actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/node-setup@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public